version: "3.5"
services:
  api1: &api
    build: .
    hostname: api1
    container_name: api1
    depends_on:
      - postgres
      - redis
    expose:
      - "8080"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "0.7GB"

  api2: # API - Instância 02
    <<: *api
    hostname: api2
    container_name: api2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"

  postgres:
    image: postgres:latest
    container_name: rinhadb
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf

    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.2GB"

  redis:
    image: redis:latest
    container_name: rinhacache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save "" --appendonly no --protected-mode no
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    driver: host
    name: rinha-nt
