server:
  port: ${SERVER_PORT:8080}
  http2:
    enabled: true

spring:
  r2dbc:
    name: rinha-datasource
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jackson:
    deserialization:
      accept-float-as-int: false

  cache:
    type: ${CACHE_TYPE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      timeout: ${REDIS_TIMEOUT}
