spring:

  datasource:
    name: rinha-datasource
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}

    hikari:
      connection-timeout: ${POOL_DATA_CONNECTION_TIMEOUT:30000}
      minimum-idle: ${POOL_DATA_MINIMUM_IDLE:1}
      maximum-pool-size: ${POOL_DATA_MAXIMUM_POOL_SIZE:10}
      idle-timeout: ${POOL_DATA_IDLE_TIMEOUT:600000}
      max-lifetime: ${POOL_DATA_MAX_LIFE_TIME:1800000}
      auto-commit: ${POOL_DATA_AUTO_COMMIT:true}

  cache:
    type: ${CACHE_TYPE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      timeout: ${REDIS_TIMEOUT}