spring:

  datasource:
    name: rinha-datasource
    url: jdbc:postgresql://localhost:5432/rinhadb
    username: rinha
    password: rinha
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000