version: "3.5"
services:
  api1: &api
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: rinha-dev
    hostname: api1
    container_name: api1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    network_mode: host
    env_file:
      - ./config/.env
    environment:
      SERVER_PORT: 8080

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/pessoas?t=jose || exit 1"]
      start_interval: 4s
      retries: 10
      interval: 1s
      timeout: 0.80s

  api2:
    <<: *api
    image: rinha-dev
    hostname: api2
    container_name: api2
    environment:
      SERVER_PORT: 8081

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/pessoas?t=jose || exit 1"]
      start_interval: 4s
      retries: 10
      interval: 1s
      timeout: 0.80s

  nginx: # Load Balancer
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    network_mode: host

  postgres:
    image: postgres:16.2
    container_name: rinhadb
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    network_mode: host

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf

    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinhadb -h localhost -p 5432"]
      start_interval: 1s
      retries: 10
      interval: 0.50s
      timeout: 0.50s

  redis:
    image: redis:latest
    container_name: rinhacache
    network_mode: host
    volumes:
      - redis-data:/data
    command: redis-server --save "" --appendonly no --protected-mode no

volumes:
  postgres-data:
  redis-data: